//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by passwin.rc
//
#define IDC_MYICON                      2
#define IDADD                           2
#define ID_ABOUT                        2
#define IDOK2                           3
#define ID_NEWPW                        3
#define IDDEL                           4
#define IDOPT                           5
#define IDS_FINDRESFAILURE              50
#define IDS_INITAILIZATION              51
#define IDS_LOCKRESFAILURE              52
#define IDS_LOADRESFAILURE              53
#define IDS_LOADSTRFAILURE              54
#define IDS_MEMALLOCFAILURE             55
#define IDS_MEMLOCKFAILURE              56
#define IDS_NOHINSTANCE                 57
#define IDS_NOHOOK                      58
#define IDS_NOTEMPLATE                  59
#define IDS_STRUCTSIZE                  60
#define IDS_CREATEICFAILURE             61
#define IDS_DNDMMISMATCH                62
#define IDS_GETDEVMODEFAIL              63
#define IDS_INITFAILURE                 64
#define IDS_LOADDRVFAILURE              65
#define IDS_NODEFAULTPRN                66
#define IDS_NODEVICES                   67
#define IDS_PARSEFAILURE                68
#define IDS_RETDEFFSAILURE              69
#define IDS_SETUPFAILURE                70
#define IDS_NOFONTS                     71
#define IDS_GLOBALFREEDEVMODE           72
#define IDS_GLOBALFREEDEVNAME           73
#define IDS_PD_RETURNDC                 74
#define IDS_CREATEDLG                   75
#define IDS_SETABORTPROC                76
#define IDS_STARTDOC                    77
#define IDS_STARTPAGE                   78
#define IDS_DELETEDC                    79
#define IDS_DESTROYWINDOW               80
#define IDS_SP_ERROR                    81
#define IDS_SP_OUTOFDISK                82
#define IDS_SP_OUTOFMEMORY              83
#define IDS_SP_PICKLISTFULL             84
#define IDS_NOPICKS                     85
#define IDS_DELETEPICKSOK               86
#define IDS_LOAD_ACCELERATORS           87
#define IDS_SE_UPDATEWINDOW             88
#define IDS_SE_GETDC                    89
#define IDS_SE_SELECTOBJECT             90
#define IDS_SE_TEXTMETRICS              91
#define IDS_SE_INVALIDATE               92
#define IDS_SE_GETCLIENTRECT            93
#define IDS_SE_BITBLT                   94
#define IDS_SE_POSTQUIT                 95
#define IDS_SE_ENDPAINT                 96
#define IDS_SE_LOCALALLOC               97
#define IDS_SE_LOCALLOCK                98
#define IDS_SE_LOCALFREE                99
#define IDD_PASSWIN_DIALOG              102
#define IDD_ABOUTBOX                    103
#define IDS_APP_TITLE                   103
#define IDM_ABOUT                       104
#define IDM_EXIT                        105
#define IDS_HELLO                       106
#define IDI_PASSWIN                     107
#define IDI_SMALL                       108
#define IDC_PASSWIN                     109
#define ECB_F2                          110
#define IDS_VERSION                     110
#define IDC_MAIN_EDIT                   111
#define IDS_COPYRIGHT                   111
#define IDS_ABORT                       112
#define WM_MESS                         112
#define IDR_MAINFRAME                   128
#define IDD_MAIN                        129
#define IDD_ENTERPW                     130
#define IDD_CHANGEMPW                   131
#define IDD_EDITDIALOG                  132
#define IDD_ADDSYS                      133
#define IDD_DIALOG1                     135
#define IDD_OPTIONS                     135
#define IDD_DISPLAYSYS                  137
#define IDD_CHANGESYS                   138
#define IDD_GENPW                       156
#define IDD_EDITSCHEMA                  157
#define IDS_SE_GLOBALALLOC              160
#define IDS_SE_SETTIMER                 161
#define IDS_SE_KILLTIMER                162
#define IDS_SE_GLOBALFREE               163
#define IDS_SE_GLOBALLOCK               164
#define IDS_SE_POLYLINE                 165
#define IDS_SE_RELEASEDC                166
#define IDS_SE_DELETEOBJECT             167
#define IDS_SETPIXEL                    168
#define IDS_DIALOGFAILURE               169
#define IDS_REGISTERMSGFAIL             170
#define IDS_DEFAULTDIFFERENT            171
#define IDS_PRINTERNOTFOUND             172
#define IDS_MAXLESSTHANMIN              173
#define IDS_BUFFERTOOSMALL              174
#define IDS_INVALIDFILENAME             175
#define IDS_SUBCLASSFAILURE             176
#define IDS_BUFFERLENGTHZERO            177
#define IDS_UNKNOWNERROR                178
#define IDD_MANAGEGLOBALOPTIONS         179
#define IDS_FILEFORMAT1                 179
#define IDS_FILEFORMAT2                 180
#define IDD_MANAGEDBFILEOPTIONS         181
#define IDS_FILEFORMAT3                 181
#define IDS_CRYPTFORMAT1                182
#define IDS_CRYPTFORMAT2                183
#define IDS_CRYPTFORMAT3                184
#define IDS_SETTINGSFILECRYPT1          187
#define IDS_SETTINGSFILECRYPT2          188
#define IDS_SETTINGSCHECKSUMCRYPT1      189
#define IDS_SETTINGSCHECKSUMCRYPT2      190
#define IDS_SETTINGSCHECKSUMCRYPT3      191
#define IDS_FILEFORMAT4                 192
#define IDS_FILEFORMAT5                 193
#define IDS_FILEFORMAT6                 194
#define IDS_FILEFORMAT7                 195
#define IDC_COMBO1                      1000
#define IDC_EDIT1                       1001
#define IDC_WEBLOC                      1002
#define IDC_NEWMPW                      1003
#define IDC_USERACC                     1003
#define IDC_CONFMPW                     1004
#define IDC_USERPW                      1004
#define IDCHANGE                        1005
#define IDC_SYSCOMBO                    1006
#define IDC_SYSNAME                     1007
#define IDC_CRECLEAR                    1008
#define IDC_READCLEAR                   1009
#define IDC_EDIT2                       1009
#define IDC_SYSLOC                      1009
#define IDC_THEWORD                     1009
#define IDC_EDITMINBACKUPAGE            1009
#define IDC_EDITMINVECTORLENGTH         1009
#define IDC_MERGEFILES                  1010
#define IDC_EDIT3                       1010
#define IDC_SYSUN                       1010
#define IDC_SYSACC                      1010
#define IDC_REMOTE_PW                   1010
#define IDC_CLEARALL                    1011
#define IDC_EDIT4                       1011
#define IDC_SYSPW                       1011
#define ID_EDIT                         1012
#define IDC_STATIC_DATE                 1016
#define IDC_STATIC_SAVED                1017
#define IDC_STATIC_NUMSYS               1018
#define IDC_STATIC_SEED                 1019
#define IDC_STATIC_FOLDER_LOCATION      1019
#define IDC_STATIC_FILEFORMAT           1020
#define IDC_STATIC_SAVEDATE             1021
#define IDC_STATIC_SAVELOCAL            1022
#define IDC_BUTTONSCHEMA                1022
#define IDC_OUTPUTTYPE2                 1023
#define IDC_BUTTONTEST                  1024
#define IDC_BUTTONGENUN                 1025
#define IDC_BUTTONGENPW                 1026
#define IDC_ARCHIVE                     1027
#define IDC_LOWERCASE                   1028
#define IDC_UPPERCASE                   1029
#define IDC_NUMBERS                     1030
#define IDC_ALL                         1031
#define IDC_CUSTOM                      1032
#define IDC_FIRSTCHAR                   1033
#define IDC_SPINWORDLENGTH              1034
#define IDC_REGEN                       1035
#define IDC_WORDLENGTH                  1036
#define IDC_CUSTOMSET                   1037
#define IDACCEPT                        1038
#define IDC_FORCEONE                    1039
#define IDC_STATIC_SAVEDATE_LABLE       1040
#define IDC_STATIC_SAVELOCAL_LABLE      1041
#define IDC_NUMBERAUX                   1043
#define IDC_SPINAUX                     1044
#define IDC_WRITEFILE                   1046
#define IDC_GLOBALOPTIONS               1047
#define IDC_MANAGEDBOPTIONS             1048
#define IDC_ENCRYPTSETTINGSFILE         1049
#define IDC_ENCRYPTCHECKSUM             1050
#define IDC_SPINMAXBACKUPS              1052
#define IDC_EDITMAXBACKUPS              1053
#define IDC_SPINMINBACKUPAGE            1054
#define IDC_STATICMAXBACKUPS            1055
#define IDC_STATICMINBACKUPAGE          1056
#define IDC_STATICBACKUPBOX             1057
#define IDC_CHECKSUM                    1058
#define IDC_STATICSETTINGSFILEENCRYPTION 1059
#define IDC_COMBOFILEFORMAT             1060
#define IDC_STATICOUTPUTFILEFORMAT      1061
#define IDC_SPINNUMBERHASHCALLS         1062
#define IDC_EDITNUMBERHASHCALLS         1063
#define IDC_CHECKAUTONUMBERCALLS        1065
#define IDC_STATICNUMBERCALL            1066
#define IDC_BUTTONSUGGESTHASH           1067
#define IDC_STATICENCRYPTTYPE           1068
#define IDC_COMBOENCRYPTFORMAT          1069
#define IDC_STATICENCRYPTCOUNTS         1070
#define IDC_RADIOENCRYPTFLAGS           1071
#define IDC_RADIONOENCRYPTFLAGS         1072
#define IDC_STATICMINVECTORLENGTH       1073
#define IDC_CHECKAUTOMINVECTORLEN       1074
#define IDC_SPINMINVECTORLENGTH         1075
#define IDC_BUTTONMANAGECUSTOMCHARSET   1076
#define IDC_BUTTONMANAGESERVER          1077
#define IDC_BUTTONRESTORBACKUP          1078
#define IDC_CHECKSHOWPASSWORDS          1079
#define IDC_BUTTONADD2                  1080
#define IDC_CHECKVISABLEACCOUNT         1081
#define IDC_CHECKVISABLEPW              1082
#define IDC_STATICDROPLISTTITLE         1083
#define IDC_REBULDSETTINGS              1084
#define IDC_ADVANEDSETTINGS             1085
#define IDC_REBUILDDATABASE             1086
#define IDC_HELPMAIN                    1087
#define IDC_REGEX                       1089
#define IDC_STATIC2                     1090
#define IDC_PINOPEN                     1091
#define IDC_STATIC4                     1092
#define IDC_STATIC3                     1093
#define IDC_STATIC_1001                 1094
#define IDC_REMOTE_TYPE                 1096
#define IDC_REMOTE_ADD                  1097
#define IDC_REMOTE_UN                   1098
#define IDC_STATIC_1004                 1099
#define IDC_STATIC_1003                 1100
#define IDC_STATIC_1002                 1101
#define IDC_REMOTE_VIEWPW               1102
#define IDC_NETADDRESS1                 1104
#define IDC_OPYS_REMSYNC                1105
#define IDC_MANGLOB_MANSERVSET          1106
#define IDC_OPYS_RESTORBACKUP           1107
#define IDC_ABOUT_REMOTE                1108
#define IDC_CLOSE                       1110
#define IDC_BUILDINFO                   1111
#define IDC_BRANCH                      1112
#define IDC_COMMIT                      1113
#define IDS_FILEFORMAT8                 1357
#define IDR_IDB_HAPPY_SAFE1             18721
#define IDB_HAPPY_SAFE                  18724
#define IDR_TEXTFILE2                   18727
#define IDD_ADVANCEDSETTINGS            18728
#define IDD_REMOTE_SETTINGS             18731
#define IDD_CACSTATUS                   18735
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        18737
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1112
#define _APS_NEXT_SYMED_VALUE           113
#endif
#endif
